/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "auth": {
        "errors": {
            "wrong_login_or_password": string;
        };
    };
    "main": {
        "messages": {
            "server_port": string;
            "incoming_req": string;
            "sentry": string;
        };
        "doc": {
            "title": string;
            "description": string;
        };
    };
};
export type I18nPath = Path<I18nTranslations>;
